site_name: Flipper Zero Dev
theme:
  name: 'material'
markdown_extensions:
  - admonition
nav:
  - Home: /
  - Classes: /Classes
  - Namespaces: /Namespaces
  - Modules: /Modules
  - Files: /Files
  - Related Pages: /Pages
  - Examples: /Examples