name: 'Run in docker'
inputs:
  run:  # id of input
    description: 'A command to run'
    required: true
    default: ''
runs:
  using: 'docker'
  image: '${{ github.run_id }}/../../../docker/Dockerfile'
  args:
    - ${{ inputs.run }}
