name: Update docker

on: 
  push:
    paths:
      - 'docker/**'
      - .github/workflows/docker.yml
  
# env:
#     DOCKER_IMAGE: flipper-zero/flipperzero-firmware-community

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: flipper-zero/flipperzero-firmware-community
          file: docker/Dockerfile
          push: true
          tags: app:latest
